from __future__ import annotations

import re


_EXACT_SHORT_NAMES = {
    "CONSIGNADO DELTA RECEIVABLES I FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS": "Delta Consig.",
    "MT CONSIGNADO PRIVADO I FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS": "MT Consig. I",
    "BTG PACTUAL CERES CONFINA FUNDO DE INVESTIMENTO NAS CADEIAS PRODUTIVAS DO AGRONEGÓCIO RESP LIMITADA": "Ceres Confina",
    "PLGN MARKETPLACE FUNDO DE INVESTIMENTO EM COTAS DE FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS": "PLGN Marketplace",
    "V CDT 1 FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS RESPONSABILIDADE LIMITADA": "V CDT 1",
    "CLASSE CONSIGNADO PRIVADO DO MT GLOBAL FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS RESP LIMITADA": "MT Global CP",
    "MERCADO CRÉDITO FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS RESPONSABILIDADE LIMITADA": "MC 0",
    "MERCADO CRÉDITO I BRASIL FIDC SEGMENTO FINANCEIRO DE RESPONSABILIDADE LIMITADA": "MC I",
    "MERCADO CRÉDITO II BRASIL FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS DE RESPONSABILIDADE LIMITADA": "MC II",
    "MERCADO CRÉDITO MERCHANT FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS": "MC Merchant",
    "SELLER FIDC SEGMENTO MEIOS DE PAGAMENTO DE RESPONSABILIDADE LIMITADA": "Sellers I",
    "SELLER II FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS SEGMENTO MEIOS DE PAGAMENTO RESP LTDA": "Sellers II",
    "SELLER 3 FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS SEGMENTO MEIOS DE PAGAMENTO DE RESP LIMITADA": "Sellers III",
    "CRÉDITO UNIVERSITÁRIO FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS - RESPONSABILIDADE LIMITADA;": "Pravaler I",
    "PRAVALER CRÉDITO UNIVERSITÁRIO II FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS - RESP LIMITADAL": "Pravaler II",
    "CREDITO UNIVERSITARIO III FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS - RESPONSABILIDADE LIMITADA": "Pravaler III",
    "CRÉDITO UNIVERSITÁRIO IV FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS - RESPONSABILIDADE LIMITADA": "Pravaler IV",
}

_PREFIX_SHORT_NAMES = (
    ("CLOUDWALK KICK ASS II", "CW Kick Ass II"),
    ("CLOUDWALK KICK ASS I", "CW Kick Ass I"),
    ("CLOUDWALK AKIRA II", "CW Akira II"),
    ("CLOUDWALK AKIRA I", "CW Akira I"),
    ("CLOUDWALK BIG PICTURE IV", "CW Big Pic. IV"),
    ("CLOUDWALK BIG PICTURE III", "CW Big Pic. III"),
    ("CLOUDWALK BIG PICTURE II", "CW Big Pic. II"),
    ("CLOUDWALK BIG PICTURE I", "CW Big Pic. I"),
    ("CLOUDWALK A.I.", "CW A.I."),
    ("CLOUDWALK PI", "CW PI"),
    ("CLOUDWALK BELA", "CW Bela"),
    ("CARTÃO DE COMPRA SUPPLIER FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS II", "Supplier II"),
    ("CARTÃO DE COMPRA SUPPLIER", "Supplier I"),
    ("ENDURANCE", "Endurance"),
    ("ESTRATÉGIA VINCULADA II", "Estrat. Vinc. II"),
    ("ESTRATÉGIA VINCULADA I", "Estrat. Vinc. I"),
    ("FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS PAGSEGURO I", "PagSeguro I"),
    ("FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS BV - CRÉDITO DE VEÍCULOS", "BV Veículos"),
    ("SUMUP SMART IV", "SumUp Smart IV"),
    ("SUMUP SOLO", "SumUp Solo"),
    ("VTK", "VTK"),
    ("PINE INSS III", "Pine INSS III"),
    ("FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS ANGÁ FGTS I", "Angá FGTS I"),
    ("ANGÁ FGTS III", "Angá FGTS III"),
    ("QUATÁ FDC FGTS", "Quatá FGTS"),
)

_LEGAL_TERMS_RE = re.compile(
    r"\b(FUNDO|DE|INVESTIMENTO|EM|DIREITOS|CREDIT[ÓO]RIOS|FIDC|RESPONSABILIDADE|LIMITADA|RESP|LTDA|SEGMENTO)\b",
    flags=re.IGNORECASE,
)


def short_fund_name(value: object, *, max_length: int = 28) -> str:
    text = re.sub(r"\s+", " ", str(value or "").strip())
    if not text:
        return ""
    key = text.upper()
    if key in _EXACT_SHORT_NAMES:
        return _EXACT_SHORT_NAMES[key]
    for prefix, short_name in _PREFIX_SHORT_NAMES:
        if key.startswith(prefix):
            return short_name
    cleaned = _LEGAL_TERMS_RE.sub(" ", text)
    cleaned = re.sub(r"\s+", " ", cleaned).strip(" -;")
    if not cleaned:
        cleaned = text
    if len(cleaned) <= max_length:
        return cleaned
    return cleaned[: max_length - 3].rstrip(" -;") + "..."
