[theme]
primaryColor = "#ff5a00"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f5f2"
textColor = "#25282d"

[server]
headless = true
maxUploadSize = 50
enableStaticServing = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
